version: '2'
services:
    message-app:
        #文件下载不下来时
        #docker login --username=100006379862 ccr.ccs.tencentyun.com
        #password : videon123
        image: ccr.ccs.tencentyun.com/liujc/card:0.0.2
        volumes:
            - ~/res:/home/work/res
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - TZ=Asia/Shanghai
        ports:
            - 9999:9999
        devices:
            - /dev/ttyUSB0:/dev/ttyUSB0
        privileged: true
        tty: true